name: Android CI

on:
  push:
    branches: [ main, develop, production ]
  pull_request:
    branches: [ main, develop, production ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create dummy google-services.json
      run: |
        echo '{
          "project_info": {
            "project_number": "123456789",
            "project_id": "dummy-project",
            "storage_bucket": "dummy-project.appspot.com"
          },
          "client": [{
            "client_info": {
              "mobilesdk_app_id": "1:123456789:android:abcdef123456",
              "android_client_info": {
                "package_name": "com.pineapple.capture"
              }
            },
            "api_key": [{
              "current_key": "dummy_api_key"
            }],
            "oauth_client": [],
            "services": {
              "appinvite_service": {
                "other_platform_oauth_client": []
              }
            }
          }]
        }' > app/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --stacktrace

    - name: Run Tests
      run: ./gradlew test 
